spellername = "Northern Haida"
spellerversion = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Northern Haida spellchecker"
hdn = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Northern Haida, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
hdn = "TRANSLATE: A spellchecker for Northern Haida, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.hdn"

[windows]
system_product_code = "{94B977DF-352A-4D47-82EC-72CD755EA1F3}_is1"
legacy_product_codes = [
    { value = "4C74F840-7F3C-475A-8D98-3ABB7A5D9B1C", kind = "nsis" },
    { value = "0B7DDC57-C32C-4A23-95DB-A69D70159423", kind = "nsis" }
]
extra_locales = { hdn-CA = "hdn" }
