template = "https://github.com/giellalt/template-lang-und"
rev_id = 283
template_sha = "bfef967c632b9041975725ec13da8c2dfe66b74e"

[replacements]
__GLOTTOLOG_ID__ = "nort2938"
__REPO__ = "lang-hdn"
__UND2C__ = "hdn"
__UNDEFINED__ = "Northern Haida"
__UND__ = "hdn"
