template = "https://github.com/giellalt/template-lang-und"
rev_id = 286
template_sha = "f08cd05b163db5f27bd203f19e51ee67c3266676"

[replacements]
__GLOTTOLOG_ID__ = "nort2938"
__REPO__ = "lang-hdn"
__UND2C__ = "hdn"
__UNDEFINED__ = "Northern Haida"
__UND__ = "hdn"
