[package]
name = "hdn"
human_name = "Northern Haida"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.hdn]
filename = "hdn-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-hdn"
platform = "windows"
uuid = "4C74F840-7F3C-475A-8D98-3ABB7A5D9B1C"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.hdn"
package = "speller-hdn"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-hdn-mso"
platform = "windows"
uuid = "0B7DDC57-C32C-4A23-95DB-A69D70159423"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-hdn"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
